# HyprEmoji Configuration

# Keybind to open hypremoji
bind = SUPER, period, exec, hypremoji

# Window rules for HyprEmoji
windowrule = float on, match:title HyprEmoji
windowrule = move cursor -50% -5%, match:title HyprEmoji
